[package]
name = "quicksweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.7", features = ["dynamic"] }
tap = "1.0"
itertools = "0.10"
derive_more = "0.99"
rand = "0.8"
iyes_loopless = "0.5"
strum = "0.24"
strum_macros = "0.24"
bevy_asset_loader = { version = "0.11", features = ["stageless"] }

anyhow = "*" # bound by bevy
