[package]
name = "quicksweeper"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
bevy_dylib = [ "bevy/dynamic" ]

[dependencies]
bevy = { version = "0.8" }
bevy_egui = "0.16"
egui = "0.19"
tap = "1.0"
itertools = "0.10"
derive_more = "0.99"
rand = "0.8"
iyes_loopless = "0.8"
strum = "0.24"
strum_macros = "0.24"
bevy_asset_loader = { version = "0.13", features = ["stageless"] }

anyhow = "*" # bound by bevy
